services:
  database:
    build:
      dockerfile: containers/postgres/Dockerfile
      context: .
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_USER: mach1
      DB_PASSWORD: mach1
      DB_NAME: mach1
    volumes:
      - db-vol:/var/lib/postgresql/data
    networks:
      db-net:
  api:
    build:
      dockerfile: containers/koa/Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://mach1:mach1@database:5432/mach1
    ports:
      - "3000:3000"
    networks:
      db-net:
      service-net:
    depends_on:
      - database
  webapp:
    build:
      dockerfile: containers/frontend/Dockerfile
      context: .
    environment:
      VUE_APP_API_URL: http://localhost:8080
      VUE_APP_API_PATH: /api
      VUE_APP_STREAM_URL: http://localhost:8080
    volumes:
      - webapp-vol:/www
      - upload-vol:/share/sound
    ports:
      - "8080:80"
      - "443:443"
      - "1935:1935"
    networks:
      service-net:
    depends_on:
      - api


volumes:
  db-vol:
    name: m1-spatial-postgres-vol
    external: true
  webapp-vol:
    name: m1-spatial-webapp-vol
    external: true
  upload-vol:
    name: m1-spatial-upload-vol
    external: true

networks:
  db-net:
    name: m1-spatial-postgres-net
    external: true
  service-net:
    name: m1-spatial-service-net
    external: true
