#!/usr/bin/env bash
set -e

PSGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 \
     --username "$POSTGRES_USER" \
     --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD' CREATEDB VALID UNTIL 'infinity';

CREATE DATABASE $DB_NAME
  WITH ENCODING ='UTF8'
  OWNER =$DB_USER
  CONNECTION LIMIT =-1;
EOSQL
